# Generated by Django 3.1.3 on 2020-12-10 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20201210_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='last4',
            field=models.CharField(blank=True, help_text="The user's last 4 credit card digits, if they exist", max_length=4),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
