# Generated by Django 3.1.3 on 2020-12-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201210_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
    ]
