# Generated by Django 3.1.3 on 2020-12-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription',
            field=models.CharField(blank=True, help_text="The user's Stripe Customer object, if it exists", max_length=100),
        ),
    ]
