# Generated by Django 3.1.3 on 2021-02-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201210_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tracking',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
