# Generated by Django 3.1.3 on 2021-02-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210212_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
